# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='next_ref_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_ref', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='prev_ref_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_ref', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
